popup ui:
  - changed-files:
      - any-glob-to-any-file:
          - spotlightPopup.js
          - popup/**
          - stylesheet.css
preferences:
  - changed-files:
      - any-glob-to-any-file:
          - prefs.js
          - prefs/**
keybinding:
  - changed-files:
      - any-glob-to-any-file:
          - services/core/keybinding.js
clipboard:
  - changed-files:
      - any-glob-to-any-file:
          - services/clipboard/**
          - popup/clipboardView.js
          - popup/clipboardPopup.js
emoji:
  - changed-files:
      - any-glob-to-any-file:
          - services/emoji/**
          - popup/emojiView.js
          - popup/emojiPopup.js
          - data/emojis.json
          - data/emojis.db
metadata and schema:
  - changed-files:
      - any-glob-to-any-file:
          - metadata.json
          - schemas/**
core extension:
  - changed-files:
      - any-glob-to-any-file:
          - extension.js
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
ci and github config:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
build scripts:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/**
translations:
  - changed-files:
      - any-glob-to-any-file:
          - locale/**
