popup ui:
  - changed-files:
      - any-glob-to-any-file:
          - lib/ui/spotlightPopup.js
          - lib/ui/**
          - stylesheet.css
preferences:
  - changed-files:
      - any-glob-to-any-file:
          - prefs.js
          - prefs/**
keybinding:
  - changed-files:
      - any-glob-to-any-file:
          - lib/core/keybinding.js

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
ci and github config:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
build scripts:
  - changed-files:
      - any-glob-to-any-file:
          - scripts/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
          - .github/dependabot.yml
